# Generated by Django 3.0.3 on 2020-06-05 05:28

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Any',
            fields=[
                ('any_key', models.AutoField(default=10000, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('JAName_First', models.CharField(default='', max_length=50)),
                ('JAName_Last', models.CharField(default='', max_length=50)),
                ('JAMob_num', models.CharField(blank=True, default=9876543210, max_length=10, null=True)),
                ('j5text', models.TextField(default='', max_length=255)),
                ('J5_Cost', models.CharField(default='', max_length=10)),
                ('JAEmail', models.EmailField(default='', max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.CharField(choices=[('Accepted', 'ACCEPTED'), ('Changes', 'CHANGES'), ('Default', 'DEFAULT'), ('Rejected', 'REJECTED')], default='Default', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Daan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donate_Reason', models.CharField(default='', max_length=250)),
                ('Donation', models.CharField(default='', max_length=10)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JEducation',
            fields=[
                ('education_key', models.AutoField(default=10000, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('JEName_First', models.CharField(default='', max_length=50)),
                ('JEName_Last', models.CharField(default='', max_length=50)),
                ('JEMob_num', models.CharField(blank=True, default=9876543210, max_length=10, null=True)),
                ('J1_Name_First', models.CharField(default='', max_length=50)),
                ('J1_Name_Last', models.CharField(default='', max_length=50)),
                ('J1_Standard', models.CharField(default='', max_length=10)),
                ('J1_Fees', models.CharField(default='', max_length=10)),
                ('J1_Paidfees', models.CharField(default='', max_length=10)),
                ('J1_Paiddate', models.DateField(blank=True, default=datetime.date.today, max_length=10, null=True)),
                ('J1_Rempaidfees', models.CharField(default='', max_length=10)),
                ('J1_Receipt', models.FileField(blank=True, null=True, upload_to='Educational_receipt')),
                ('j1text', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('JEEmail', models.EmailField(default='', max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.CharField(choices=[('Accepted', 'ACCEPTED'), ('Changes', 'CHANGES'), ('Default', 'DEFAULT'), ('Rejected', 'REJECTED')], default='Default', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JMedical',
            fields=[
                ('medical_key', models.AutoField(default=10000, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('JMName_First', models.CharField(default='', max_length=50)),
                ('JMName_Last', models.CharField(default='', max_length=50)),
                ('JMMob_num', models.CharField(blank=True, default=9876543210, max_length=10, null=True)),
                ('J2_Name_First', models.CharField(default='', max_length=50)),
                ('J2_Name_Last', models.CharField(default='', max_length=50)),
                ('j2text', models.TextField(default='', max_length=255)),
                ('J2_HospiName', models.CharField(default='', max_length=20)),
                ('J2_DocName', models.CharField(default='', max_length=20)),
                ('J2_Cost', models.CharField(default='', max_length=10)),
                ('J2_Receipt', models.FileField(blank=True, null=True, upload_to='Medical_receipt')),
                ('JMEmail', models.EmailField(default='', max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.CharField(choices=[('Accepted', 'ACCEPTED'), ('Changes', 'CHANGES'), ('Default', 'DEFAULT'), ('Rejected', 'REJECTED')], default='Default', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JPardes',
            fields=[
                ('pardes_key', models.AutoField(default=10000, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('JPName_First', models.CharField(default='', max_length=50)),
                ('JPName_Last', models.CharField(default='', max_length=50)),
                ('JPMob_num', models.CharField(blank=True, default=9876543210, max_length=10, null=True)),
                ('J4_Name_First', models.CharField(default='', max_length=50)),
                ('J4_Name_Last', models.CharField(default='', max_length=50)),
                ('j4text', models.TextField(default='', max_length=255)),
                ('J4_muddat', models.CharField(default='', max_length=20)),
                ('J4_Cost', models.CharField(default='', max_length=20)),
                ('JPEmail', models.EmailField(default='', max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.CharField(choices=[('Accepted', 'ACCEPTED'), ('Changes', 'CHANGES'), ('Default', 'DEFAULT'), ('Rejected', 'REJECTED')], default='Default', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JSamajik',
            fields=[
                ('samajik_key', models.AutoField(default=10000, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('JSName_First', models.CharField(default='', max_length=50)),
                ('JSName_Last', models.CharField(default='', max_length=50)),
                ('JSMob_num', models.CharField(blank=True, default=9876543210, max_length=10, null=True)),
                ('j3text', models.TextField(default='', max_length=255)),
                ('J3_Cost', models.CharField(default='', max_length=15)),
                ('JSEmail', models.EmailField(default='', max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.CharField(choices=[('Accepted', 'ACCEPTED'), ('Changes', 'CHANGES'), ('Default', 'DEFAULT'), ('Rejected', 'REJECTED')], default='Default', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaheliRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D1Name_Last', models.CharField(default='', max_length=20)),
                ('D1Name_First', models.CharField(default='', max_length=20)),
                ('DMob_num', models.CharField(default='', max_length=10)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
