# Generated by Django 3.0.3 on 2020-06-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='any',
            name='any_key',
            field=models.AutoField(default=50000, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jmedical',
            name='medical_key',
            field=models.AutoField(default=20000, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jpardes',
            name='pardes_key',
            field=models.AutoField(default=40000, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jsamajik',
            name='samajik_key',
            field=models.AutoField(default=30000, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
