# Generated by Django 3.0.3 on 2020-06-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatapp', '0002_auto_20200605_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='any',
            name='any_key',
            field=models.AutoField(default=50000, max_length=6, primary_key=True, serialize=False),
        ),
    ]
