# Generated by Django 3.0.3 on 2020-06-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatapp', '0006_auto_20200605_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='any',
            name='any_key',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jmedical',
            name='medical_key',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jpardes',
            name='pardes_key',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jsamajik',
            name='samajik_key',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
