# Generated by Django 3.0.3 on 2020-06-06 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatapp', '0007_auto_20200605_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLogin',
            fields=[
                ('data_login_key', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('D1Name_Last', models.CharField(default='', max_length=20)),
                ('D1Name_First', models.CharField(default='', max_length=20)),
                ('DMob_num', models.CharField(default='', max_length=10)),
                ('DEmail', models.EmailField(default='', max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='PaheliRegister',
        ),
        migrations.RemoveField(
            model_name='daan',
            name='id',
        ),
        migrations.AddField(
            model_name='daan',
            name='Donar_mob_num',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='daan',
            name='anyd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daan',
            name='daan_key',
            field=models.AutoField(default=90000, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='daan',
            name='imamezamin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daan',
            name='khayrat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daan',
            name='khums',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daan',
            name='zakat',
            field=models.BooleanField(default=False),
        ),
    ]
