# Generated by Django 3.0.3 on 2020-06-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatapp', '0008_auto_20200606_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='any',
            name='any_key',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datalogin',
            name='data_login_key',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jeducation',
            name='education_key',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jmedical',
            name='medical_key',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jpardes',
            name='pardes_key',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jsamajik',
            name='samajik_key',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
