# Generated by Django 3.0.3 on 2020-06-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hujjatapp', '0009_auto_20200606_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daan',
            name='daan_key',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
